# Generated by Django 4.1.4 on 2022-12-20 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('V2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expired_Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty_fee_amount', models.FloatField(default=0.0)),
                ('payment_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_user', to='V2.payment_user')),
            ],
        ),
    ]
